---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx for HTTPS
  template:
    src: resources/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes